name: Build and Push to Daily Site
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Inject GIT Slug/Short Variables # Exposes git variables in a slug format (/ turns to - etc).
        uses: rlespinasse/github-slug-action@v3.x
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files.
            yarn
            yarn elm-svelte-app build:storybook
      - name: Rename 'storybook-static' to Current Branch Name
        run: mv packages/elm-svelte-app/storybook-static packages/elm-svelte-app/${{ env.GITHUB_REF_SLUG }}
      - name: Push to Daily Site 🚀
        run: |
            mkdir tmp
            git config --global user.email ${{ github.actor }}
            git config --global user.name ${{ github.actor }}
            git clone --single-branch --branch master "https://${{ secrets.API_TOKEN_GITHUB }}@github.com/robinjac/daily-sites.git" tmp
            rm -rf tmp/awesome-apps/${{ env.GITHUB_REF_SLUG }}/
            cp -a packages/elm-svelte-app/${{ env.GITHUB_REF_SLUG }}/. tmp/awesome-apps/${{ env.GITHUB_REF_SLUG }}/
            cd tmp
            git add .
            git commit --allow-empty --message "[GHA] Push from ${{ env.GITHUB_REF_SLUG }}"
            git push -u origin HEAD:master
